add first dragging functionality / fix error on reload due to printing
FabianHeidelberg/RPCompanion pull request #1
Opened 2018-07-30 14:32 UTC by timgrossmann

### Entity Dragging
- Change data model to a simpler structure
- fix for page reload error caused by println function
- added basic functionality for dragging

> Don't merge yet

2018-07-31 11:54 UTC, timgrossmann commented
@paulsonnentag @FabianHeidelberg Ready for review

2018-07-31 20:38 UTC, paulsonnentag requested changes
Gefällt mir sehr gut, besonders die Linienanimation sieht klasse aus. Hab ein paar Anmerkungen gemacht, was mir aufgefallen ist

2018-07-31 20:38 UTC, paulsonnentag commented on src/rp-companion/master.cljs
> +            next-y (second next-pos)]
hier könntest du destructuring verwenden
```clojure
(let [[next-x next-y] next-pos]
   ...)
```

2018-07-31 20:38 UTC, paulsonnentag commented on src/rp-companion/master.cljs
> +            (when (or (not= x next-x) (not= y next-y))
Ich würde next position standardmäßig auf null setzen, wenn keine position gesetzt wurde, dann kann man einfacher checken ob es eine nexte position gibt oder nicht.

2018-07-31 20:38 UTC, paulsonnentag commented on src/rp-companion/master.cljs
> +                      :cy y
Wenn du die position mit css transforms setzt könntest du eine einfache css transition für die transform property definieren und die blobs würden sich automatisch animiert bewegen. Nur so als nettes Zusatzfeature

2018-07-31 20:38 UTC, paulsonnentag commented on src/rp-companion/master.cljs
> +                                              [key (assoc entity :position new-position)])) entities)))]
Wenn du mehrere funktionen nacheinander anwendest kannst du das threading macro verwenden

https://clojure.org/guides/threading_macros

das macht es ein bisschen besser lesbar

2018-08-01 12:11 UTC, timgrossmann commented
![ezgif com-crop](https://user-images.githubusercontent.com/16529337/43520904-b2cb16fc-9594-11e8-9620-f61a2a6641a4.gif)

2018-08-01 13:09 UTC, paulsonnentag approved these changes

2018-08-01 14:01 UTC, merged